/**
 * Ready-made particle graphs. Each is a plain graph (same shape the compiler
 * takes) demonstrating how the small nodes compose into a class of effect.
 * Loading a preset replaces the current graph in the editor (until Apply,
 * nothing touches the component).
 */

export const PARTICLE_PRESETS = {
  Fire: {
    nodes: [
      { id: "emit", type: "emitCone", props: { radius: 0.18, angle: 14 }, position: { x: -60, y: 40 } },
      { id: "speed", type: "float", props: { value: 1.6 }, position: { x: -60, y: 230 } },
      { id: "vel", type: "multiply", props: {}, position: { x: 170, y: 120 } },
      { id: "heat", type: "buoyancy", props: { strength: 4, flicker: 1 }, position: { x: -60, y: 360 } },
      { id: "turb", type: "turbulence", props: { frequency: 1.4, strength: 1.6, speed: 0.6 }, position: { x: -60, y: 520 } },
      { id: "drag", type: "drag", props: { amount: 0.6 }, position: { x: -60, y: 690 } },
      { id: "f1", type: "add", props: {}, position: { x: 170, y: 430 } },
      { id: "f2", type: "add", props: {}, position: { x: 170, y: 590 } },
      { id: "ramp", type: "gradient", props: { from: "#ffe08a", to: "#ff2200" }, position: { x: 170, y: 260 } },
      { id: "shrink", type: "remap", props: { inMin: 0, inMax: 1, outMin: 0.3, outMax: 0.05 }, position: { x: 170, y: 740 } },
      { id: "sys", type: "system", props: { capacity: 3000, lifetime: 1.3, lifetimeJitter: 0.4, additive: true }, position: { x: 470, y: 180 } },
    ],
    edges: [
      { source: "emit", sourceHandle: "pos", target: "sys", targetHandle: "position" },
      { source: "emit", sourceHandle: "dir", target: "vel", targetHandle: "a" },
      { source: "speed", sourceHandle: "out", target: "vel", targetHandle: "b" },
      { source: "vel", sourceHandle: "out", target: "sys", targetHandle: "velocity" },
      { source: "heat", sourceHandle: "out", target: "f1", targetHandle: "a" },
      { source: "turb", sourceHandle: "out", target: "f1", targetHandle: "b" },
      { source: "f1", sourceHandle: "out", target: "f2", targetHandle: "a" },
      { source: "drag", sourceHandle: "out", target: "f2", targetHandle: "b" },
      { source: "f2", sourceHandle: "out", target: "sys", targetHandle: "force" },
      { source: "ramp", sourceHandle: "out", target: "sys", targetHandle: "color" },
      { source: "shrink", sourceHandle: "out", target: "sys", targetHandle: "size" },
    ],
  },

  Smoke: {
    nodes: [
      { id: "emit", type: "emitSphere", props: { radius: 0.2 }, position: { x: -60, y: 40 } },
      { id: "speed", type: "float", props: { value: 0.5 }, position: { x: -60, y: 230 } },
      { id: "vel", type: "multiply", props: {}, position: { x: 170, y: 120 } },
      { id: "rise", type: "buoyancy", props: { strength: 1.2, flicker: 0.3 }, position: { x: -60, y: 360 } },
      { id: "turb", type: "turbulence", props: { frequency: 0.5, strength: 0.8, speed: 0.25 }, position: { x: -60, y: 520 } },
      { id: "windN", type: "wind", props: { direction: [1, 0, 0.2], strength: 0.35, gustiness: 0.8, gustFrequency: 0.4 }, position: { x: -60, y: 690 } },
      { id: "drag", type: "drag", props: { amount: 0.8 }, position: { x: -60, y: 860 } },
      { id: "f1", type: "add", props: {}, position: { x: 170, y: 430 } },
      { id: "f2", type: "add", props: {}, position: { x: 170, y: 590 } },
      { id: "f3", type: "add", props: {}, position: { x: 170, y: 750 } },
      { id: "ramp", type: "gradient", props: { from: "#7a7a80", to: "#26262e" }, position: { x: 170, y: 260 } },
      { id: "grow", type: "remap", props: { inMin: 0, inMax: 1, outMin: 0.15, outMax: 1.2 }, position: { x: 450, y: 620 } },
      { id: "fade", type: "remap", props: { inMin: 0, inMax: 1, outMin: 0.35, outMax: 0 }, position: { x: 450, y: 780 } },
      { id: "sys", type: "system", props: { capacity: 1200, lifetime: 4, lifetimeJitter: 0.4, additive: false }, position: { x: 720, y: 180 } },
    ],
    edges: [
      { source: "emit", sourceHandle: "pos", target: "sys", targetHandle: "position" },
      { source: "emit", sourceHandle: "dir", target: "vel", targetHandle: "a" },
      { source: "speed", sourceHandle: "out", target: "vel", targetHandle: "b" },
      { source: "vel", sourceHandle: "out", target: "sys", targetHandle: "velocity" },
      { source: "rise", sourceHandle: "out", target: "f1", targetHandle: "a" },
      { source: "turb", sourceHandle: "out", target: "f1", targetHandle: "b" },
      { source: "f1", sourceHandle: "out", target: "f2", targetHandle: "a" },
      { source: "windN", sourceHandle: "out", target: "f2", targetHandle: "b" },
      { source: "f2", sourceHandle: "out", target: "f3", targetHandle: "a" },
      { source: "drag", sourceHandle: "out", target: "f3", targetHandle: "b" },
      { source: "f3", sourceHandle: "out", target: "sys", targetHandle: "force" },
      { source: "ramp", sourceHandle: "out", target: "sys", targetHandle: "color" },
      { source: "grow", sourceHandle: "out", target: "sys", targetHandle: "size" },
      { source: "fade", sourceHandle: "out", target: "sys", targetHandle: "opacity" },
    ],
  },

  Fountain: {
    nodes: [
      { id: "emit", type: "emitCone", props: { radius: 0.06, angle: 9 }, position: { x: -60, y: 40 } },
      { id: "speed", type: "float", props: { value: 6.5 }, position: { x: -60, y: 230 } },
      { id: "vel", type: "multiply", props: {}, position: { x: 170, y: 120 } },
      { id: "grav", type: "gravity", props: { vector: [0, -9.8, 0] }, position: { x: 170, y: 300 } },
      { id: "ramp", type: "gradient", props: { from: "#bfe3ff", to: "#2a6cff" }, position: { x: 170, y: 460 } },
      { id: "size", type: "float", props: { value: 0.06 }, position: { x: 170, y: 620 } },
      { id: "sys", type: "system", props: { capacity: 6000, lifetime: 3, lifetimeJitter: 0.25, additive: true, floor: "bounce", floorY: 0, bounce: 0.45 }, position: { x: 470, y: 160 } },
    ],
    edges: [
      { source: "emit", sourceHandle: "pos", target: "sys", targetHandle: "position" },
      { source: "emit", sourceHandle: "dir", target: "vel", targetHandle: "a" },
      { source: "speed", sourceHandle: "out", target: "vel", targetHandle: "b" },
      { source: "vel", sourceHandle: "out", target: "sys", targetHandle: "velocity" },
      { source: "grav", sourceHandle: "out", target: "sys", targetHandle: "force" },
      { source: "ramp", sourceHandle: "out", target: "sys", targetHandle: "color" },
      { source: "size", sourceHandle: "out", target: "sys", targetHandle: "size" },
    ],
  },

  Snow: {
    nodes: [
      { id: "emit", type: "emitBox", props: { size: [10, 0.2, 10] }, position: { x: -60, y: 40 } },
      { id: "split", type: "split", props: {}, position: { x: -60, y: 200 } },
      { id: "height", type: "float", props: { value: 8 }, position: { x: -60, y: 360 } },
      { id: "spawn", type: "combine", props: {}, position: { x: 110, y: 220 } },
      { id: "fall", type: "vec3", props: { value: [0, -0.9, 0] }, position: { x: -60, y: 530 } },
      { id: "windN", type: "wind", props: { direction: [1, 0, 0.3], strength: 0.4, gustiness: 1, gustFrequency: 0.3 }, position: { x: -60, y: 700 } },
      { id: "sway", type: "turbulence", props: { frequency: 0.35, strength: 0.4, speed: 0.3 }, position: { x: -60, y: 870 } },
      { id: "drag", type: "drag", props: { amount: 0.4 }, position: { x: -60, y: 1040 } },
      { id: "f1", type: "add", props: {}, position: { x: 170, y: 770 } },
      { id: "f2", type: "add", props: {}, position: { x: 170, y: 940 } },
      { id: "white", type: "color", props: { value: "#ffffff" }, position: { x: 170, y: 160 } },
      { id: "size", type: "float", props: { value: 0.045 }, position: { x: 170, y: 300 } },
      { id: "sys", type: "system", props: { capacity: 4000, lifetime: 9, lifetimeJitter: 0.35, additive: false, floor: "kill", floorY: 0 }, position: { x: 470, y: 140 } },
    ],
    edges: [
      { source: "emit", sourceHandle: "pos", target: "split", targetHandle: "v" },
      { source: "split", sourceHandle: "x", target: "spawn", targetHandle: "x" },
      { source: "height", sourceHandle: "out", target: "spawn", targetHandle: "y" },
      { source: "split", sourceHandle: "z", target: "spawn", targetHandle: "z" },
      { source: "spawn", sourceHandle: "out", target: "sys", targetHandle: "position" },
      { source: "fall", sourceHandle: "out", target: "sys", targetHandle: "velocity" },
      { source: "windN", sourceHandle: "out", target: "f1", targetHandle: "a" },
      { source: "sway", sourceHandle: "out", target: "f1", targetHandle: "b" },
      { source: "f1", sourceHandle: "out", target: "f2", targetHandle: "a" },
      { source: "drag", sourceHandle: "out", target: "f2", targetHandle: "b" },
      { source: "f2", sourceHandle: "out", target: "sys", targetHandle: "force" },
      { source: "white", sourceHandle: "out", target: "sys", targetHandle: "color" },
      { source: "size", sourceHandle: "out", target: "sys", targetHandle: "size" },
    ],
  },

  "Magic Vortex": {
    nodes: [
      { id: "emit", type: "emitCircle", props: { radius: 1.3 }, position: { x: -60, y: 40 } },
      { id: "inward", type: "float", props: { value: -0.25 }, position: { x: -60, y: 230 } },
      { id: "vel", type: "multiply", props: {}, position: { x: 170, y: 120 } },
      { id: "swirl", type: "vortex", props: { center: [0, 0, 0], axis: [0, 1, 0], strength: 6, pull: 0.9 }, position: { x: -60, y: 380 } },
      { id: "lift", type: "attract", props: { point: [0, 1.8, 0], strength: 2.5, falloff: 0.8 }, position: { x: -60, y: 560 } },
      { id: "wisp", type: "turbulence", props: { frequency: 1.1, strength: 1, speed: 0.5 }, position: { x: -60, y: 730 } },
      { id: "f1", type: "add", props: {}, position: { x: 170, y: 460 } },
      { id: "f2", type: "add", props: {}, position: { x: 170, y: 630 } },
      { id: "ramp", type: "gradient", props: { from: "#7fe3ff", to: "#c26bff" }, position: { x: 170, y: 260 } },
      { id: "shrink", type: "remap", props: { inMin: 0, inMax: 1, outMin: 0.12, outMax: 0.02 }, position: { x: 450, y: 560 } },
      { id: "sys", type: "system", props: { capacity: 8000, lifetime: 3, lifetimeJitter: 0.3, additive: true }, position: { x: 470, y: 160 } },
    ],
    edges: [
      { source: "emit", sourceHandle: "pos", target: "sys", targetHandle: "position" },
      { source: "emit", sourceHandle: "dir", target: "vel", targetHandle: "a" },
      { source: "inward", sourceHandle: "out", target: "vel", targetHandle: "b" },
      { source: "vel", sourceHandle: "out", target: "sys", targetHandle: "velocity" },
      { source: "swirl", sourceHandle: "out", target: "f1", targetHandle: "a" },
      { source: "lift", sourceHandle: "out", target: "f1", targetHandle: "b" },
      { source: "f1", sourceHandle: "out", target: "f2", targetHandle: "a" },
      { source: "wisp", sourceHandle: "out", target: "f2", targetHandle: "b" },
      { source: "f2", sourceHandle: "out", target: "sys", targetHandle: "force" },
      { source: "ramp", sourceHandle: "out", target: "sys", targetHandle: "color" },
      { source: "shrink", sourceHandle: "out", target: "sys", targetHandle: "size" },
    ],
  },
};
