// Vite ?raw imports — bundles the .d.ts files as string constants in the
// final JS so we can copy them into the user's project on creation / open.
// The engine ships its declarations with the editor bundle; we never need to
// reach into the engine source tree at runtime.
import ENGINE_DTS from "../engine/script-types/engine.d.ts?raw";
import EDITOR_DTS from "../engine/script-types/editor.d.ts?raw";
import THREE_DTS from "../engine/script-types/three.d.ts?raw";
// three's own version, so the vendored declarations can be version-gated
// against the three the engine actually runs.
import { REVISION } from "three/webgpu";

/**
 * The shape of the user's project root after we scaffold TypeScript support.
 * - `<project>/engine-types/engine.d.ts`  — copied verbatim from the engine
 * - `<project>/engine-types/three.d.ts`   — engine-side notes, no declarations
 * - `<project>/engine-types/three/`       — vendored `@types/three`
 * - `<project>/engine-types/.three-version` — version gate for the above
 * - `<project>/tsconfig.json`             — exposes `engine` + `three` via paths
 * - `<project>/project-events.d.ts`       — the project's own declared events.
 *   At the ROOT rather than in `engine-types/`, because that folder is in
 *   `exclude` and a module augmentation only applies when the file is part of
 *   the program. See `projectEventTypes.js`.
 *
 * The user's IDE reads `tsconfig.json` from the open file's nearest parent,
 * so as long as they have a script somewhere under the project root, the IDE
 * resolves `import { Script } from "engine"` to our copied typings.
 *
 * ## Why three's declarations are vendored per-project
 *
 * `engine.d.ts` re-exports three's real types rather than redeclaring them (it
 * used to hand-declare ~170 lines of three's math API, which silently drifted
 * — it advertised `Quaternion.inverse()` years after three renamed it to
 * `invert()`). That means the project needs three's declarations reachable, or
 * every re-exported type quietly degrades to `any`: `skipLibCheck` suppresses
 * the unresolved import inside `engine.d.ts`, so the failure mode is not an
 * error, it is autocomplete that just stops knowing anything.
 *
 * A project has no `node_modules`, so we copy `@types/three` in from the app's
 * bundled resources (see the `scaffold_three_types` Tauri command). It is
 * version-locked to the engine's `three` in package.json, so the editor's
 * autocomplete matches what the script runtime actually exposes.
 *
 * `noEmit: true` keeps the user's project from accidentally compiling its
 * scripts (the engine runtime does that itself at play time).
 * `include` is permissive — it scans every script-like file under the
 * project root for autocomplete, while excluding our copied engine-types so
 * the IDE doesn't double-resolve them.
 */
const TSCONFIG_JSON = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "bundler",
      lib: ["ES2022", "DOM", "DOM.Iterable"],
      allowJs: true,
      checkJs: false,
      noEmit: true,
      isolatedModules: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      skipLibCheck: true,
      experimentalDecorators: true,
      useDefineForClassFields: false,
      strict: false,
      paths: {
        engine: ["./engine-types/engine.d.ts"],
        // Editor-only surface: `Editor`, @executeInEditMode, @menuItem. Safe to
        // import from a gameplay script — only *calling* it outside the editor
        // throws — so it belongs in every project's paths, not a separate one.
        editor: ["./engine-types/editor.d.ts"],
        // All three entry points a script can import. At runtime bare "three"
        // is routed to the three/webgpu build (there must only ever be one
        // three instance — see src/engine/scriptRuntime.js), so a script that
        // wants WebGPU/TSL-only symbols should import "three/webgpu" to keep
        // types and runtime in agreement.
        three: ["./engine-types/three/build/three.module.d.ts"],
        "three/webgpu": ["./engine-types/three/build/three.webgpu.d.ts"],
        "three/tsl": ["./engine-types/three/build/three.tsl.d.ts"],
        "three/addons/*": ["./engine-types/three/examples/jsm/*"],
      },
    },
    include: ["**/*.ts", "**/*.js", "**/*.tsx", "**/*.jsx"],
    exclude: ["node_modules", "engine-types", "dist"],
  },
  null,
  2,
);

/** A short comment in the scaffolded tsconfig so future maintainers know
 *  what generated the file and how to regenerate it if the engine's typings
 *  change. (Keep in sync with the message in this file's doc comment.) */
const TSCONFIG_BANNER =
  "// Generated by Three Engine on project creation / open. Re-run\n" +
  "// `scaffoldProjectTypes(projectRoot)` to refresh after engine updates.\n";

/** Marker file recording which three version's declarations are vendored. */
const VERSION_MARKER = ".three-version";

/**
 * Copies `@types/three` into the project unless the marker file already
 * records this exact three version. ~1000 small files, so we do want the gate,
 * but it is a single Tauri call rather than a write per file.
 *
 * Failure is non-fatal and deliberately loud: scripts still run without
 * declarations, the user just loses three's autocomplete, and silently
 * degrading to `any` is exactly the failure this whole mechanism exists to
 * prevent.
 */
async function scaffoldThreeTypes(invoke, engineTypesDir) {
  const markerPath = `${engineTypesDir}/${VERSION_MARKER}`;
  try {
    const existing = await invoke("read_text_file", { path: markerPath });
    if (existing.trim() === REVISION) return;
  } catch {
    // No marker (or unreadable) — treat as "not scaffolded yet".
  }
  try {
    const count = await invoke("scaffold_three_types", {
      destDir: `${engineTypesDir}/three`,
    });
    await invoke("save_scene", { path: markerPath, contents: `${REVISION}\n` });
    console.log(`Vendored three r${REVISION} type declarations (${count} files)`);
  } catch (err) {
    console.warn(
      `Couldn't vendor three's type declarations — three autocomplete will be unavailable in this project: ${err}`,
    );
  }
}

/**
 * Adds `paths` entries the engine has gained since a project's tsconfig was
 * written, without touching anything else in it.
 *
 * Existing projects keep their hand-editable tsconfig (we only ever write one
 * when none exists), so a new specifier — `"editor"` was the first — would
 * otherwise resolve to nothing in every project created before it shipped, and
 * `skipLibCheck` turns that into silent `any` rather than an error. The user's
 * only clue would be autocomplete quietly knowing less than it used to.
 *
 * Additive by construction: a key already present is left alone, and a config
 * we can't parse (comments, trailing commas — both legal in tsconfig, neither
 * legal in JSON) is left entirely alone rather than reformatted.
 */
const REQUIRED_PATHS = {
  editor: ["./engine-types/editor.d.ts"],
  three: ["./engine-types/three/build/three.module.d.ts"],
  "three/webgpu": ["./engine-types/three/build/three.webgpu.d.ts"],
  "three/tsl": ["./engine-types/three/build/three.tsl.d.ts"],
  "three/addons/*": ["./engine-types/three/examples/jsm/*"],
};

async function addMissingPaths(invoke, configPath) {
  let parsed;
  let raw;
  try {
    raw = await invoke("read_text_file", { path: configPath });
    parsed = JSON.parse(raw.replace(/^\s*\/\/.*$/gm, ""));
  } catch {
    return; // hand-edited into something we can't safely rewrite
  }
  const paths = parsed?.compilerOptions?.paths;
  if (!paths) return; // no paths block at all: not our generated shape
  const missing = Object.entries(REQUIRED_PATHS).filter(([key]) => !(key in paths));
  if (!missing.length) return;
  for (const [key, value] of missing) paths[key] = value;
  await invoke("save_scene", {
    path: configPath,
    contents: TSCONFIG_BANNER + JSON.stringify(parsed, null, 2) + "\n",
  });
  console.log(`Added ${missing.map(([key]) => `"${key}"`).join(", ")} to ${configPath}`);
}

/**
 * Writes the engine's `.d.ts` files, three's declarations, and a
 * `tsconfig.json` into the user's project so TypeScript-aware IDEs can resolve
 * `import ... from "engine"` and `from "three"` when editing scripts.
 *
 * Idempotent: re-running is safe and overwrites existing copies of
 * `engine-types/*.d.ts` (so engine updates propagate), but does NOT clobber a
 * user's hand-edited `tsconfig.json` — only writes one if none exists.
 */
export async function scaffoldProjectTypes(projectRoot) {
  if (!projectRoot) return;
  const { invoke } = await import("@tauri-apps/api/core");
  const engineTypesDir = `${projectRoot}/engine-types`;
  await invoke("create_dir", { path: engineTypesDir }).catch(() => {});
  // Always rewrite the .d.ts files so engine updates propagate. They're small
  // (~30 KB total) and the editor doesn't need to diff.
  await invoke("save_scene", {
    path: `${engineTypesDir}/engine.d.ts`,
    contents: ENGINE_DTS,
  });
  await invoke("save_scene", {
    path: `${engineTypesDir}/editor.d.ts`,
    contents: EDITOR_DTS,
  });
  await invoke("save_scene", {
    path: `${engineTypesDir}/three.d.ts`,
    contents: THREE_DTS,
  });
  await scaffoldThreeTypes(invoke, engineTypesDir);
  // The project's own declared events, generated from project.json's `events`
  // block. Read here rather than passed in so both callers (project open, and
  // the Assets panel's manual refresh) get it without either having to know the
  // catalog exists. Note the destination is the project ROOT, not
  // `engine-types/` — see projectEventTypes.js for why that is load-bearing.
  try {
    const meta = JSON.parse(await invoke("read_text_file", { path: `${projectRoot}/project.json` }));
    const { writeProjectEventTypes, syncProjectEventTypesToMonaco } = await import(
      "./projectEventTypes.js"
    );
    const generated = await writeProjectEventTypes(projectRoot, meta?.events);
    await syncProjectEventTypesToMonaco(generated);
  } catch {
    // No project.json, or unreadable — nothing to generate from.
  }
  // The project's own script classes and hook names, which is what makes
  // `getScript`/`dispatch` type-checked. Same root placement, same reason.
  // Not fatal and not awaited-for-correctness: a project whose script types
  // are missing still runs, it just autocompletes less.
  try {
    const { writeProjectScriptTypes, syncProjectScriptTypesToMonaco } = await import(
      "./projectScriptTypes.js"
    );
    await syncProjectScriptTypesToMonaco(await writeProjectScriptTypes(projectRoot));
  } catch (err) {
    console.warn(`Couldn't generate script declarations: ${err}`);
  }
  // tsconfig.json: only write if missing. Users sometimes have their own
  // (e.g. with extra strict flags); we shouldn't silently overwrite those.
  // A `jsconfig.json` counts as "configured" too — it's the same shape, just
  // with `allowJs: true` implied, and is what the engine workspace itself uses.
  const tsconfigPath = `${projectRoot}/tsconfig.json`;
  const jsconfigPath = `${projectRoot}/jsconfig.json`;
  let hasConfig = false;
  for (const candidate of [tsconfigPath, jsconfigPath]) {
    try {
      await invoke("load_scene", { path: candidate });
      hasConfig = true;
      await addMissingPaths(invoke, candidate);
      break;
    } catch {
      // not present — try the next candidate
    }
  }
  if (!hasConfig) {
    await invoke("save_scene", {
      path: tsconfigPath,
      contents: TSCONFIG_BANNER + TSCONFIG_JSON + "\n",
    });
    console.log(`Wrote ${tsconfigPath} for engine type autocomplete`);
  }
}
