// Vite ?raw imports — bundles the .d.ts files as string constants in the
// final JS so we can copy them into the user's project on creation / open.
// The engine ships its declarations with the editor bundle; we never need to
// reach into the engine source tree at runtime.
import ENGINE_DTS from "../engine/script-types/engine.d.ts?raw";
import THREE_DTS from "../engine/script-types/three.d.ts?raw";

/**
 * The shape of the user's project root after we scaffold TypeScript support.
 * - `<project>/engine-types/engine.d.ts`  — copied verbatim from the engine
 * - `<project>/engine-types/three.d.ts`   — minimal three ambient forwarding
 * - `<project>/tsconfig.json`             — exposes `engine` via paths + module
 *
 * The user's IDE reads `tsconfig.json` from the open file's nearest parent,
 * so as long as they have a script somewhere under the project root, the IDE
 * resolves `import { Script } from "engine"` to our copied typings.
 *
 * `noEmit: true` keeps the user's project from accidentally compiling its
 * scripts (the engine runtime does that itself at play time).
 * `include` is permissive — it scans every script-like file under the
 * project root for autocomplete, while excluding our copied engine-types so
 * the IDE doesn't double-resolve them.
 */
const TSCONFIG_JSON = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "bundler",
      lib: ["ES2022", "DOM", "DOM.Iterable"],
      allowJs: true,
      checkJs: false,
      noEmit: true,
      isolatedModules: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      skipLibCheck: true,
      experimentalDecorators: true,
      useDefineForClassFields: false,
      strict: false,
      paths: {
        engine: ["./engine-types/engine.d.ts"],
      },
    },
    include: [
      "**/*.ts",
      "**/*.js",
      "**/*.tsx",
      "**/*.jsx",
    ],
    exclude: ["node_modules", "engine-types", "dist"],
  },
  null,
  2,
);

/** A short comment in the scaffolded tsconfig so future maintainers know
 *  what generated the file and how to regenerate it if the engine's typings
 *  change. (Keep in sync with the message in this file's doc comment.) */
const TSCONFIG_BANNER =
  "// Generated by Three Engine on project creation / open. Re-run\n" +
  "// `scaffoldProjectTypes(projectRoot)` to refresh after engine updates.\n";

/**
 * Writes the engine's `.d.ts` files and a `tsconfig.json` into the user's
 * project so TypeScript-aware IDEs can resolve `import ... from "engine"`
 * when editing scripts. Idempotent: re-running is safe and overwrites
 * existing copies of `engine-types/*.d.ts` (so engine updates propagate),
 * but does NOT clobber a user's hand-edited `tsconfig.json` — only writes
 * one if none exists.
 */
export async function scaffoldProjectTypes(projectRoot) {
  if (!projectRoot) return;
  const { invoke } = await import("@tauri-apps/api/core");
  const engineTypesDir = `${projectRoot}/engine-types`;
  await invoke("create_dir", { path: engineTypesDir }).catch(() => {});
  // Always rewrite the .d.ts files so engine updates propagate. They're small
  // (~10 KB total) and the editor doesn't need to diff.
  await invoke("save_scene", {
    path: `${engineTypesDir}/engine.d.ts`,
    contents: ENGINE_DTS,
  });
  await invoke("save_scene", {
    path: `${engineTypesDir}/three.d.ts`,
    contents: THREE_DTS,
  });
  // tsconfig.json: only write if missing. Users sometimes have their own
  // (e.g. with extra strict flags); we shouldn't silently overwrite those.
  // A `jsconfig.json` counts as "configured" too — it's the same shape, just
  // with `allowJs: true` implied, and is what the engine workspace itself uses.
  const tsconfigPath = `${projectRoot}/tsconfig.json`;
  const jsconfigPath = `${projectRoot}/jsconfig.json`;
  let hasConfig = false;
  for (const candidate of [tsconfigPath, jsconfigPath]) {
    try {
      await invoke("load_scene", { path: candidate });
      hasConfig = true;
      break;
    } catch {
      // not present — try the next candidate
    }
  }
  if (!hasConfig) {
    await invoke("save_scene", {
      path: tsconfigPath,
      contents: TSCONFIG_BANNER + TSCONFIG_JSON + "\n",
    });
    console.log(`Wrote ${tsconfigPath} for engine type autocomplete`);
  }
}