import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three/webgpu';
import { Entity } from '../src/engine/Entity.js';
import { ColliderComponent } from '../src/modules/physics-rapier/ColliderComponent.js';
import { ClothMeshColliderField } from '../src/engine/clothMeshColliders.js';

function fixture(props = {}, options = {}) {
  const engine = { entities: new Map(), playing: false };
  const entity = new Entity(engine,{id:'surface',name:'Arch'});
  engine.entities.set(entity.id,entity);
  const collider = new ColliderComponent({shape:'concave',...props});
  entity.components.set('collider',collider); collider.entity=entity;
  const field = new ClothMeshColliderField(engine,options); field.addUser();
  const add = (geometry,position=[0,0,0]) => {
    const mesh = new THREE.Mesh(geometry); mesh.position.fromArray(position);
    mesh.userData.entityId=entity.id; entity.object3D.add(mesh); return mesh;
  };
  return {engine,entity,collider,field,add};
}
function intersects(field,origin,direction,skip=-1) {
  const ray = new THREE.Ray(new THREE.Vector3(...origin),new THREE.Vector3(...direction));
  const data=field.data, point=new THREE.Vector3();
  let index=0, visits=0;
  while(index<field.countUniform.value) {
    assert.ok(visits++<field.countUniform.value+1,'stackless traversal terminates');
    const base=index*20;
    const box=new THREE.Box3(new THREE.Vector3().fromArray(data,base),new THREE.Vector3().fromArray(data,base+4));
    if(!ray.intersectsBox(box)){index=data[base+3];continue;}
    if(data[base+7]===1){
      if(data[base+19]!==skip && ray.intersectTriangle(new THREE.Vector3().fromArray(data,base+8),new THREE.Vector3().fromArray(data,base+12),new THREE.Vector3().fromArray(data,base+16),false,point))return point.clone();
      index=data[base+3];
    }else index++;
  }
  return null;
}

test('concave arch preserves opening and stackless BVH hits actual side surfaces',()=>{
  const {field,add}=fixture({autoGenerated:true});
  add(new THREE.BoxGeometry(1,4,1),[-2,0,0]);
  add(new THREE.BoxGeometry(1,4,1),[2,0,0]);
  add(new THREE.BoxGeometry(5,1,1),[0,2,0]);
  field.refresh();
  assert.equal(field.triangleCount,36);
  assert.equal(field.countUniform.value,71);
  assert.equal(intersects(field,[0,0,5],[0,0,-1]),null,'open doorway remains empty');
  assert.ok(intersects(field,[2,0,5],[0,0,-1]));
  assert.ok(intersects(field,[0,2,5],[0,0,-1]));
  assert.equal(intersects(field,[2,0,5],[0,0,-1],field.entityIndices.get('surface')),null,'per-simulation owner skip');
});

test('cooked simplified concave takes precedence; mesh uses unsimplified cooked source',()=>{
  const {engine,entity,collider,field,add}=fixture();
  add(new THREE.BoxGeometry(100,100,100));
  const triangle={vertices:new Float32Array([-1,-1,0,1,-1,0,0,1,0]),indices:new Uint32Array([0,1,2])};
  const cooked={vertices:new Float32Array([-1,-1,2,1,-1,2,0,1,2]),indices:new Uint32Array([0,1,2]),concave:triangle};
  engine.physics={getCookedColliderGeometry:()=>cooked};
  field.refresh(); assert.equal(field.triangleCount,1);
  assert.equal(intersects(field,[0,0,5],[0,0,-1]).z,0);
  collider.props.shape='mesh'; field.refresh();
  assert.equal(intersects(field,[0,0,5],[0,0,-1]).z,2);
  assert.equal(field.entityIndices.get(entity.id),0);
});

test('world scale, local collider rotation and offset match Rapier geometry pose',()=>{
  const {field,entity,add}=fixture({offset:[1,0,0],rotation:[0,90,0]});
  add(new THREE.PlaneGeometry(2,2));
  entity.object3D.position.set(10,0,0); entity.object3D.scale.set(-2,3,1);
  field.refresh();
  const hit=intersects(field,[20,0,0],[-1,0,0]);
  assert.ok(hit); assert.ok(Math.abs(hit.x-8)<1e-5);
});

test('unchanged refresh is cached, transforms and source versions invalidate, proxies excluded',()=>{
  const {field,entity,add}=fixture({autoGenerated:true});
  const mesh=add(new THREE.PlaneGeometry(2,2));
  const proxy=add(new THREE.BoxGeometry(100,100,100));proxy.userData.vfxSimulation='cloth';
  field.refresh();assert.equal(field.triangleCount,2);
  const version=field.revision; field.refresh();assert.equal(field.revision,version);
  entity.object3D.position.z=2;field.refresh();assert.equal(field.revision,version+1);
  assert.equal(intersects(field,[0,0,5],[0,0,-1]).z,2);
  mesh.geometry.attributes.position.setZ(0,1);mesh.geometry.attributes.position.needsUpdate=true;
  field.refresh();assert.equal(field.revision,version+2);
});

test('triangle limit rejects entire collider visibly; disabled ancestors and triggers remove field',()=>{
  const {field,collider,entity,add}=fixture({}, {maxTriangles:1});
  add(new THREE.PlaneGeometry(2,2));field.refresh();
  assert.equal(field.countUniform.value,0); assert.match(field.error,/2 triangles.*budget/);
  collider.props.isSensor=true;field.refresh();assert.equal(field.error,null);
  collider.props.isSensor=false;entity.parent={enabledInEditor:false};field.refresh();assert.equal(field.countUniform.value,0);
});

 test('closed shell certification handles seams, opposite disconnected winding, open and inconsistent shells',async()=>{
  const {certifyClosedCollisionShells}=await import('../src/engine/clothMeshColliders.js');
  const {mergeCollisionMeshes,collectCollisionMesh}=await import('../src/modules/physics-rapier/collisionGeometry.js');
  const source=g=>collectCollisionMesh(new THREE.Mesh(g),{bakeRootScale:false});
  const box=source(new THREE.BoxGeometry(2,2,2));
  assert.ok([...certifyClosedCollisionShells(box)].every(sign=>sign===1));
  const reversed={vertices:new Float32Array(box.vertices),indices:new Uint32Array(box.indices)};
  for(let i=0;i<reversed.vertices.length;i+=3)reversed.vertices[i]+=10;
  for(let i=0;i<reversed.indices.length;i+=3)[reversed.indices[i],reversed.indices[i+1]]=[reversed.indices[i+1],reversed.indices[i]];
  const both=certifyClosedCollisionShells(mergeCollisionMeshes([box,reversed]));
  assert.deepEqual([...both], [...Array(12).fill(1),...Array(12).fill(-1)]);
  assert.ok([...certifyClosedCollisionShells(source(new THREE.PlaneGeometry(2,2)))].every(sign=>sign===0));
  [box.indices[0],box.indices[1]]=[box.indices[1],box.indices[0]];
  assert.ok([...certifyClosedCollisionShells(box)].every(sign=>sign===0));
});

test('packed closed signs account for mirrored transforms, open branches skip, last user releases cache',()=>{
  const {entity,field,add}=fixture();
  add(new THREE.BoxGeometry(2,2,2));entity.object3D.scale.x=-1;field.refresh();
  assert.equal(field.diagnostics[0].closed,true);assert.equal(field.diagnostics[0].closedTriangles,12);
  assert.equal(field.data[11],1,'internal closed descendant flag');
  for(let i=0;i<field.countUniform.value;i++)if(field.data[i*20+7])assert.equal(field.data[i*20+11],-1);
  field.removeUser();assert.equal(field.countUniform.value,0);assert.equal(field._sources.size,0);
  field.addUser();field.refresh();assert.equal(field.triangleCount,12);
});

test('global shell ids remain separate across opposite-winding islands and collider owners',()=>{
  const {engine,entity,field,add}=fixture();
  add(new THREE.BoxGeometry(2,2,2),[-3,0,0]);
  const reverse=new THREE.BoxGeometry(2,2,2);const index=reverse.index.array;
  for(let i=0;i<index.length;i+=3)[index[i],index[i+1]]=[index[i+1],index[i]];
  add(reverse,[3,0,0]);
  const other=new Entity(engine,{id:'other'});engine.entities.set(other.id,other);
  other.components.set('collider',new ColliderComponent({shape:'concave'}));
  other.object3D.add(new THREE.Mesh(new THREE.BoxGeometry(1,1,1)));
  field.refresh();assert.equal(field.closedShellCountUniform.value,3);
  const shells=new Map();
  for(let i=0;i<field.countUniform.value;i++) {
    const base=i*20;
    if(field.data[base+7]) {
      const id=field.data[base+15], owner=field.data[base+19];
      if(!shells.has(id))shells.set(id,{owners:new Set(),signs:new Set(),count:0});
      const shell=shells.get(id);shell.owners.add(owner);shell.signs.add(field.data[base+11]);shell.count++;
    } else {
      const descendants=[];
      for(let j=i+1;j<field.data[base+3];j++)if(field.data[j*20+7])descendants.push(field.data[j*20+15]);
      assert.equal(field.data[base+15],Math.min(...descendants));
      assert.equal(field.data[base+19],Math.max(...descendants));
    }
  }
  assert.equal(shells.size,3);
  for(const shell of shells.values()){assert.equal(shell.owners.size,1);assert.equal(shell.signs.size,1);assert.equal(shell.count,12);}
  assert.deepEqual([...shells.values()].map(s=>[...s.signs][0]).sort(),[-1,1,1]);
});
