/**
 * THE AUTO-COLLIDER FLUSH MUST NOT STORM (ZERO_FREEZE_PLAN §1.4).
 *
 * The user's own boot printed
 *
 *     [engine] hierarchy-changed storm: 30 flushes within a second
 *
 * and the stack named `PhysicsSystem #flushDefaultColliders`. Every pass that
 * touched any entity emitted a scene-wide "hierarchy-changed", and that event
 * runs ~20 listeners which each walk the scene — so a scene load paid the full
 * edit fan-out thirty times to report colliders that, since 2026-09-02, attach
 * DISABLED and change nothing anybody can see.
 *
 * Rapier runs headlessly in Node (its wasm is inlined), so this drives the REAL
 * PhysicsSystem, the same way `scripts/run-physics-test.mjs` does.
 */
import test from "node:test";
import assert from "node:assert/strict";

const stubElement = () => ({
  style: {},
  appendChild() {},
  removeChild() {},
  addEventListener() {},
  removeEventListener() {},
  setAttribute() {},
  classList: { add() {}, remove() {} },
  parentElement: null,
});
globalThis.document ??= {
  body: stubElement(),
  createElement: stubElement,
  addEventListener() {},
  removeEventListener() {},
  hidden: false,
};
// See run-physics-test.mjs: Rapier's wasm-bindgen glue takes the browser path
// the moment `window` exists and then calls window.performance.now(); a stub
// without it traps with a bare "unreachable".
globalThis.window ??= {
  devicePixelRatio: 1,
  addEventListener() {},
  removeEventListener() {},
  performance: globalThis.performance,
  crypto: globalThis.crypto,
};
globalThis.requestAnimationFrame ??= (fn) => setTimeout(() => fn(performance.now()), 16);
globalThis.cancelAnimationFrame ??= (id) => clearTimeout(id);

const { Engine, registerBuiltInComponents, applyEngineModules } = await import("../src/engine/index.js");
await import("../src/modules/index.js"); // registers the module catalog
registerBuiltInComponents();

const settle = () => new Promise((resolve) => setTimeout(resolve, 30));

/**
 * Builds `count` mesh entities and reports how many scene-wide flushes the
 * AUTOMATIC COLLIDER PASS cost, separately from the ones building the tree
 * costs.
 *
 * The separation is the whole measurement: entity creation legitimately
 * announces itself (`Engine.createEntity` batches its own), and it is
 * synchronous, while the collider flush is queued to a microtask. So the
 * creation loop runs inside one `batchHierarchy` — one flush, whatever it
 * contains — and everything counted after it returns belongs to the flush.
 */
async function measureFlush(count, { startEnabled }) {
  const engine = new Engine();
  engine.config.physicsAutoColliders = { startEnabled };
  await applyEngineModules(engine, ["physics-rapier"]);
  await engine.modules.get("physics-rapier")?.ready;
  await settle();

  let flushes = 0;
  engine.on("hierarchy-changed", () => flushes++);
  const entities = [];
  engine.batchHierarchy(() => {
    for (let i = 0; i < count; i++) {
      const entity = engine.createEntity({ name: `Box${i}` });
      entity.addComponent("mesh", { geometry: "box" });
      entities.push(entity);
    }
  });
  const building = flushes;
  await settle();
  return { engine, entities, colliderFlushes: flushes - building };
}

test("attaching auto colliders that start DISABLED costs no scene-wide event at all", async () => {
  const { entities, colliderFlushes } = await measureFlush(12, { startEnabled: false });

  assert.equal(
    entities.every((e) => e.getComponent("collider")?.props.autoGenerated === true),
    true,
    "precondition: the flush attached an automatic collider to every mesh",
  );
  assert.equal(
    entities.every((e) => e.getComponent("collider").enabled === false),
    true,
    "precondition: they start disabled (the 2026-09-02 default)",
  );
  assert.equal(
    colliderFlushes,
    0,
    `a disabled auto collider adds no object, no shape and no body; got ${colliderFlushes} flushes`,
  );
});

test("attaching ENABLED auto colliders is ONE event for the whole pass, not one per entity", async () => {
  const { entities, colliderFlushes } = await measureFlush(12, { startEnabled: true });

  assert.equal(
    entities.every((e) => e.getComponent("collider")?.enabled === true),
    true,
    "precondition: the flush attached an ENABLED collider to every mesh",
  );
  assert.equal(
    colliderFlushes,
    1,
    `an enabled collider IS structure, but twelve of them are one pass; got ${colliderFlushes}`,
  );
});

test("the hatch restores the old behaviour: a disabled-collider pass announces again", async () => {
  globalThis.__physicsColliderFlushQuiet = false;
  try {
    const { colliderFlushes } = await measureFlush(6, { startEnabled: false });
    assert.ok(colliderFlushes >= 1, "with the hatch off the pass must announce as it used to");
  } finally {
    delete globalThis.__physicsColliderFlushQuiet;
  }
});
