import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three/webgpu';
import { Entity } from '../src/engine/Entity.js';
import { ColliderComponent } from '../src/modules/physics-rapier/ColliderComponent.js';
import { ParticleColliderField } from '../src/engine/particleColliders.js';

function fixture(props = {}, geometry = new THREE.BoxGeometry(4, 2, 6)) {
  const engine = { entities: new Map(), playing: false };
  const entity = new Entity(engine, { id: 'collider' });
  engine.entities.set(entity.id, entity);
  const mesh = new THREE.Mesh(geometry);
  mesh.userData.entityId = entity.id;
  entity.object3D.add(mesh);
  const collider = new ColliderComponent(props);
  collider.entity = entity;
  entity.components.set('collider', collider);
  const field = new ParticleColliderField(engine);
  field.addUser();
  return { engine, entity, mesh, collider, field };
}
const near = (actual, expected) => assert.ok(Math.abs(actual-expected)<1e-5, `${actual} != ${expected}`);

test('real Collider defaults auto-fit rendered bounds and auto-center under signed world scale', () => {
  const { entity, mesh, field } = fixture();
  mesh.position.set(2, 3, 4);
  entity.object3D.scale.set(-2, 3, 4);
  entity.object3D.position.set(10, 20, 30);
  field.refresh();
  assert.equal(field.countUniform.value, 1);
  [6,29,46].forEach((v,i)=>near(field.data[i+1],v));
  [4,3,12].forEach((v,i)=>near(field.data[7+i*4],v));
});

test('local collider rotation combines with parent pose without rotating primitive offset', () => {
  const { entity, field } = fixture({ autoFit:false, autoCenter:false, size:[2,4,6], offset:[1,0,0], rotation:[0,0,90] });
  const parent = new THREE.Group();
  parent.position.set(10,0,0);
  parent.rotation.y = Math.PI/2;
  parent.add(entity.object3D);
  field.refresh();
  near(field.data[1],10); near(field.data[3],-1);
  near(field.data[4],0); near(field.data[5],1); near(field.data[6],0);
  near(field.data[8],0); near(field.data[10],1);
});

test('default autogenerated convex uses owned geometry bounds, excluding GPU proxy and child entities', () => {
  const { entity, mesh, field } = fixture({ shape:'convex', autoGenerated:true });
  mesh.position.set(3,0,0);
  const proxy = new THREE.Mesh(new THREE.BoxGeometry(1000,1000,1000));
  proxy.userData.vfxSimulation = true;
  proxy.userData.entityId = entity.id;
  entity.object3D.add(proxy);
  const child = new THREE.Mesh(new THREE.BoxGeometry(100,100,100));
  child.userData.entityId = 'other';
  entity.object3D.add(child);
  field.refresh();
  near(field.data[1],3); near(field.data[7],2); near(field.data[11],1); near(field.data[15],3);
  assert.equal(field.entityIndices.get(entity.id),0);
});

test('sphere autofit includes scaled diagonal and capsules include their height', () => {
  const { entity, collider, field } = fixture({shape:'sphere'});
  entity.object3D.scale.set(2,1,1);
  field.refresh();
  near(field.data[7],Math.hypot(8,2,6)/2);
  Object.assign(collider.props,{shape:'capsule',autoFit:false,radius:.5,height:4});
  field.refresh(); near(field.data[7],3);
});

test('triggers and disabled ancestors are omitted; camera culling is not a physics disable', () => {
  const { engine, entity, collider, field } = fixture();
  entity.object3D.visible = false;
  field.refresh(); assert.equal(field.countUniform.value,1);
  collider.props.isSensor = true;
  field.refresh(); assert.equal(field.countUniform.value,0); assert.equal(field.entityIndices.size,0);
  collider.props.isSensor = false;
  entity.parent = { enabledInEditor:false, enabledInGame:true };
  field.refresh(); assert.equal(field.countUniform.value,0);
  engine.playing = true;
  field.refresh(); assert.equal(field.countUniform.value,1);
  collider.props.enabled = false;
  field.refresh(); assert.equal(field.countUniform.value,0);
});

test('hollow mesh colliders are not silently replaced by solid bounding boxes', () => {
  const { field } = fixture({shape:'mesh'});
  field.refresh(); assert.equal(field.countUniform.value,0);
});
