import * as THREE from "three/webgpu";
import { instancedArray, uniform } from "three/tsl";
import { collisionGeometryBounds } from "../modules/physics-rapier/collisionGeometry.js";

const MAX_COLLIDERS = 64;
// [type, center.xyz], [right.xyz, halfX|radius], [up.xyz, halfY], [forward.xyz, halfZ].
const FLOATS_PER_COLLIDER = 16;
const TYPE_BOX = 0, TYPE_SPHERE = 1;
const pos = new THREE.Vector3(), scale = new THREE.Vector3(), center = new THREE.Vector3();
const quat = new THREE.Quaternion(), localQuat = new THREE.Quaternion(), euler = new THREE.Euler();
const right = new THREE.Vector3(), up = new THREE.Vector3(), forward = new THREE.Vector3();
const size = new THREE.Vector3();

/** Resolve the authored collider pose, using the same fitting rules as Rapier.
 * Convex hulls use an oriented bounds approximation; capsules an enclosing
 * sphere. Concave/triangle/terrain shapes require a separate GPU acceleration
 * structure and are intentionally omitted, never replaced with a solid box.
 */
export function writeParticleCollider(entity, collider, data, base = 0) {
  const p = collider.props;
  const shape = p.shape ?? "box";
  if (!["box", "sphere", "capsule", "convex"].includes(shape)) return false;
  const root = entity.object3D;
  root.updateWorldMatrix(true, false);
  root.matrixWorld.decompose(pos, quat, scale);
  const sx = Math.abs(scale.x), sy = Math.abs(scale.y), sz = Math.abs(scale.z);
  const primitive = shape !== "convex";
  const bounds = (!primitive || p.autoFit || p.autoCenter)
    ? collisionGeometryBounds(root, { ownerEntityId: !primitive && p.autoGenerated ? entity.id : null }) : null;
  if (!primitive && !bounds) return false;
  const fitted = bounds && (!primitive || p.autoFit);
  if (fitted) bounds.getSize(size);
  else size.fromArray(p.size ?? [1, 1, 1]);
  euler.set(...[0, 1, 2].map(i => (p.rotation?.[i] ?? 0) * THREE.MathUtils.DEG2RAD));
  localQuat.setFromEuler(euler);
  center.set(0, 0, 0);
  if (bounds && (!primitive || p.autoCenter)) bounds.getCenter(center);
  // Convex vertices are rotated along with the shape; primitive auto-centers
  // are translations outside the collider rotation, exactly as in Rapier.
  center.multiply(scale);
  if (!primitive) center.applyQuaternion(localQuat);
  center.add(new THREE.Vector3().fromArray(p.offset ?? [0, 0, 0]).multiply(scale));
  center.applyQuaternion(quat).add(pos);
  quat.multiply(localQuat);
  right.set(1, 0, 0).applyQuaternion(quat);
  up.set(0, 1, 0).applyQuaternion(quat);
  forward.set(0, 0, 1).applyQuaternion(quat);
  let type = TYPE_BOX;
  let hx = Math.max(size.x, .001) * sx / 2;
  let hy = Math.max(size.y, .001) * sy / 2;
  let hz = Math.max(size.z, .001) * sz / 2;
  if (shape === "sphere" || shape === "capsule") {
    type = TYPE_SPHERE;
    let radius = fitted ? (shape === "sphere" ? Math.hypot(size.x*sx, size.y*sy, size.z*sz)/2 : Math.max(size.x*sx, size.z*sz)/2)
      : (p.radius ?? .5) * (shape === "sphere" ? Math.max(sx, sy, sz) : Math.max(sx, sz));
    if (shape === "capsule") radius += fitted ? Math.max((size.y*sy-radius*2)/2, .0001) : (p.height ?? 1)*sy/2;
    hx = hy = hz = radius;
  }
  const row = [type, ...center.toArray(), ...right.toArray(), hx, ...up.toArray(), hy, ...forward.toArray(), hz];
  if (!row.every(Number.isFinite) || Math.min(hx, hy, hz) <= 0) return false;
  data.set(row, base);
  return true;
}

function enabledInHierarchy(entity, playing) {
  const flag = playing ? "enabledInGame" : "enabledInEditor";
  for (let current = entity; current; current = current.parent) if (current[flag] === false) return false;
  return true;
}

/** Shared GPU collider field. Off-camera colliders remain active. */
export class ParticleColliderField {
  constructor(engine) {
    this.engine = engine;
    this.data = new Float32Array(MAX_COLLIDERS * FLOATS_PER_COLLIDER);
    this.buffer = instancedArray(this.data, "vec4");
    this.countUniform = uniform(0, "int");
    this.activeUsers = 0;
    this.entityIndices = new Map();
  }
  addUser() { this.activeUsers++; }
  removeUser() { this.activeUsers = Math.max(0, this.activeUsers - 1); }
  dispose() {
    this.entityIndices.clear();
    if (this.engine.particleColliders === this) delete this.engine.particleColliders;
  }
  refresh() {
    if (this.activeUsers <= 0) return;
    this.entityIndices.clear();
    let count = 0;
    for (const entity of this.engine.entities.values()) {
      if (count >= MAX_COLLIDERS) break;
      const collider = entity.getComponent?.("collider");
      if (!collider || collider.enabled === false || collider.props.isSensor || !enabledInHierarchy(entity, this.engine.playing)) continue;
      if (!writeParticleCollider(entity, collider, this.data, count * FLOATS_PER_COLLIDER)) continue;
      this.entityIndices.set(entity.id, count++);
    }
    this.countUniform.value = count;
    this.buffer.value.needsUpdate = true;
  }
}

export const PARTICLE_COLLIDER_TYPE_BOX = TYPE_BOX;
export const PARTICLE_COLLIDER_TYPE_SPHERE = TYPE_SPHERE;
export const PARTICLE_COLLIDER_MAX = MAX_COLLIDERS;
