import * as THREE from "three/webgpu";
import { instancedArray, uniform } from "three/tsl";
import { collisionGeometryBounds } from "../modules/physics-rapier/collisionGeometry.js";

const MAX_COLLIDERS = 64;
// [type, center.xyz], [right.xyz, halfX|radius], [up.xyz, halfY], [forward.xyz, halfZ].
const FLOATS_PER_COLLIDER = 16;
const TYPE_BOX = 0, TYPE_SPHERE = 1;
// A collider that shifted less than this in a frame counts as standing still.
const MOVE_EPSILON = 1e-4;
const pos = new THREE.Vector3(), scale = new THREE.Vector3(), center = new THREE.Vector3();
const quat = new THREE.Quaternion(), localQuat = new THREE.Quaternion(), euler = new THREE.Euler();
const right = new THREE.Vector3(), up = new THREE.Vector3(), forward = new THREE.Vector3();
const size = new THREE.Vector3();

/** Resolve the authored collider pose, using the same fitting rules as Rapier.
 * Convex hulls use an oriented bounds approximation; capsules an enclosing
 * sphere. Concave/triangle/terrain shapes require a separate GPU acceleration
 * structure and are intentionally omitted, never replaced with a solid box.
 */
export function writeParticleCollider(entity, collider, data, base = 0) {
  const p = collider.props;
  const shape = p.shape ?? "box";
  if (!["box", "sphere", "capsule", "convex"].includes(shape)) return false;
  const root = entity.object3D;
  root.updateWorldMatrix(true, false);
  root.matrixWorld.decompose(pos, quat, scale);
  const sx = Math.abs(scale.x), sy = Math.abs(scale.y), sz = Math.abs(scale.z);
  const primitive = shape !== "convex";
  const bounds = (!primitive || p.autoFit || p.autoCenter)
    ? collisionGeometryBounds(root, { ownerEntityId: !primitive && p.autoGenerated ? entity.id : null }) : null;
  if (!primitive && !bounds) return false;
  const fitted = bounds && (!primitive || p.autoFit);
  if (fitted) bounds.getSize(size);
  else size.fromArray(p.size ?? [1, 1, 1]);
  euler.set(...[0, 1, 2].map(i => (p.rotation?.[i] ?? 0) * THREE.MathUtils.DEG2RAD));
  localQuat.setFromEuler(euler);
  center.set(0, 0, 0);
  if (bounds && (!primitive || p.autoCenter)) bounds.getCenter(center);
  // Convex vertices are rotated along with the shape; primitive auto-centers
  // are translations outside the collider rotation, exactly as in Rapier.
  center.multiply(scale);
  if (!primitive) center.applyQuaternion(localQuat);
  center.add(new THREE.Vector3().fromArray(p.offset ?? [0, 0, 0]).multiply(scale));
  center.applyQuaternion(quat).add(pos);
  quat.multiply(localQuat);
  right.set(1, 0, 0).applyQuaternion(quat);
  up.set(0, 1, 0).applyQuaternion(quat);
  forward.set(0, 0, 1).applyQuaternion(quat);
  let type = TYPE_BOX;
  let hx = Math.max(size.x, .001) * sx / 2;
  let hy = Math.max(size.y, .001) * sy / 2;
  let hz = Math.max(size.z, .001) * sz / 2;
  if (shape === "sphere" || shape === "capsule") {
    type = TYPE_SPHERE;
    let radius = fitted ? (shape === "sphere" ? Math.hypot(size.x*sx, size.y*sy, size.z*sz)/2 : Math.max(size.x*sx, size.z*sz)/2)
      : (p.radius ?? .5) * (shape === "sphere" ? Math.max(sx, sy, sz) : Math.max(sx, sz));
    if (shape === "capsule") radius += fitted ? Math.max((size.y*sy-radius*2)/2, .0001) : (p.height ?? 1)*sy/2;
    hx = hy = hz = radius;
  }
  const row = [type, ...center.toArray(), ...right.toArray(), hx, ...up.toArray(), hy, ...forward.toArray(), hz];
  if (!row.every(Number.isFinite) || Math.min(hx, hy, hz) <= 0) return false;
  data.set(row, base);
  return true;
}

/**
 * ⭐ A CHARACTER IS A COLLIDER TOO, and this field could not see one.
 *
 * `PhysicsSystem.#createColliders` returns early for a character-controller
 * entity — "owns its own capsule" — so the character's shape never comes from a
 * `collider` component, and a walk that looks only for that component misses
 * the one thing in the scene the player actually moves. Reported 2026-09-08:
 * cloth *"does not react to character collider"*. It reacted to everything
 * else, which is what made it look like a cloth bug.
 *
 * Presented as the capsule the controller builds, so the field's existing
 * capsule handling applies unchanged.
 *
 * ⚠ AND THAT HANDLING IS AN ENCLOSING SPHERE (see this file's header): a
 * capsule of radius r and height h becomes a sphere of radius r + h/2. For a
 * 1.8 m character that is a 1.2 m ball, so cloth reacts about a body's width
 * early. Crude, but it is what every other capsule collider here already does,
 * and a tighter fit means a real capsule type in the field rather than a
 * special case for one entity.
 */
function characterAsCollider(entity) {
  const cc = entity.getComponent?.("charactercontroller");
  if (!cc || cc.enabled === false) return null;
  const p = cc.props;
  return {
    enabled: true,
    props: {
      shape: "capsule",
      radius: p.radius,
      height: p.height,
      offset: p.offset,
      rotation: [0, 0, 0],
      autoFit: false,
      autoCenter: false,
      isSensor: false,
    },
  };
}

function enabledInHierarchy(entity, playing) {
  const flag = playing ? "enabledInGame" : "enabledInEditor";
  for (let current = entity; current; current = current.parent) if (current[flag] === false) return false;
  return true;
}

/** Shared GPU collider field. Off-camera colliders remain active. */
export class ParticleColliderField {
  constructor(engine) {
    this.engine = engine;
    this.data = new Float32Array(MAX_COLLIDERS * FLOATS_PER_COLLIDER);
    this.buffer = instancedArray(this.data, "vec4");
    this.countUniform = uniform(0, "int");
    this.activeUsers = 0;
    this.entityIndices = new Map();
    this._scannedFrame = -1;
    // Which packed rows moved since the last scan, and where each entity's
    // collider stood then. Keyed by entity id, not by row, because a row index
    // belongs to whichever collider happened to be packed there this frame.
    this.moved = new Uint8Array(MAX_COLLIDERS);
    this._lastCentre = new Map();
  }
  addUser() { this.activeUsers++; }
  removeUser() { this.activeUsers = Math.max(0, this.activeUsers - 1); }
  dispose() {
    this.entityIndices.clear();
    if (this.engine.particleColliders === this) delete this.engine.particleColliders;
  }
  /**
   * ⛔⛔ **ONCE A FRAME, NOT ONCE PER USER.** This field is SHARED — one
   * `engine.particleColliders` serves every cloth and every particle system —
   * but it was refreshed from each one's own tick, so a full walk of every
   * entity in the level, plus a `writeParticleCollider` pose decompose for each
   * collider found, ran once per CLOTH per frame and produced the identical
   * answer every time. The cost was CLOTHS x ENTITIES.
   *
   * This is the same fault `ClothMeshColliderField.refresh` was fixed for on
   * 2026-09-08, in the other collider field; only the mesh/concave half was
   * caught then. `renderer.info.frame` increments once per rendered frame, so
   * the first user to ask does the work and the rest read what it published.
   */
  refresh() {
    if (this.activeUsers <= 0) return;
    const frame = this.engine?.renderer?.info?.frame;
    if (frame !== undefined && frame === this._scannedFrame) return;
    this._scannedFrame = frame ?? -1;
    this.entityIndices.clear();
    if (this._lastCentre.size > MAX_COLLIDERS * 2) this._lastCentre.clear();
    let count = 0;
    for (const entity of this.engine.entities.values()) {
      if (count >= MAX_COLLIDERS) break;
      const collider = characterAsCollider(entity) ?? entity.getComponent?.("collider");
      if (!collider || collider.enabled === false || collider.props.isSensor || !enabledInHierarchy(entity, this.engine.playing)) continue;
      const base = count * FLOATS_PER_COLLIDER;
      if (!writeParticleCollider(entity, collider, this.data, base)) continue;
      const cx = this.data[base + 1], cy = this.data[base + 2], cz = this.data[base + 3];
      const last = this._lastCentre.get(entity.id);
      this.moved[count] = !last || Math.abs(last[0] - cx) > MOVE_EPSILON
        || Math.abs(last[1] - cy) > MOVE_EPSILON || Math.abs(last[2] - cz) > MOVE_EPSILON ? 1 : 0;
      if (last) { last[0] = cx; last[1] = cy; last[2] = cz; } else this._lastCentre.set(entity.id, [cx, cy, cz]);
      this.entityIndices.set(entity.id, count++);
    }
    this.countUniform.value = count;
    this.buffer.value.needsUpdate = true;
  }
  /**
   * ⭐⭐⭐ **IS SOMETHING WALKING THROUGH THIS?** Conservative sphere test of a
   * simulation's own reach against every collider that MOVED this frame.
   *
   * It exists so that culling a simulation nobody is looking at cannot break
   * the one thing an unwatched cloth still has to get right: a character
   * pushing through it. A collider that is merely standing still near the
   * cloth — the wall it hangs on, the floor under it — does not qualify, because
   * a cloth at rest against static geometry stays where it is.
   *
   * The row's bound is `hypot(hx, hy, hz)`, the half-extents' diagonal, which
   * over-covers a sphere row (its three half-extents are all the radius) by
   * design: this test may only ever keep a simulation running needlessly, never
   * stop one that was needed.
   */
  nearAnyMovingCollider(centre, radius) {
    const d = this.data;
    for (let i = 0, n = this.countUniform.value; i < n; i++) {
      if (!this.moved[i]) continue;
      const b = i * FLOATS_PER_COLLIDER;
      const reach = radius + Math.hypot(d[b + 7], d[b + 11], d[b + 15]);
      const dx = d[b + 1] - centre.x, dy = d[b + 2] - centre.y, dz = d[b + 3] - centre.z;
      if (dx * dx + dy * dy + dz * dz <= reach * reach) return true;
    }
    return false;
  }
}

export const PARTICLE_COLLIDER_TYPE_BOX = TYPE_BOX;
export const PARTICLE_COLLIDER_TYPE_SPHERE = TYPE_SPHERE;
export const PARTICLE_COLLIDER_MAX = MAX_COLLIDERS;
