import * as THREE from "three/webgpu";
import { Component } from "../../engine/components/Component.js";
import { EDITOR_LAYER, PHYSICS_DEBUG_LAYER } from "../../engine/editorLayers.js";
import { physicsLayerNames } from "./layerConfig.js";
import { collisionGeometryBounds } from "./collisionGeometry.js";

const GIZMO_COLOR = 0x2df098;
const DEG2RAD = Math.PI / 180;

/**
 * Collision shape. Pairs with a Rigidbody on the same entity (or the nearest
 * ancestor Rigidbody — child colliders form a compound body). A collider with
 * no Rigidbody anywhere above it becomes static level geometry.
 *
 * `shape: "convex"` builds a solid convex hull from rendered geometry.
 * `shape: "concave"` builds a reduced triangle surface, while `shape: "mesh"`
 * preserves every source triangle. Both triangle shapes are hollow and are
 * used only on static/kinematic bodies; dynamic bodies fall back to convex.
 * `shape: "heightfield"` reads the entity's sibling Terrain component
 * (resolution/heights/size) and builds a Rapier heightfield — requires a
 * Terrain component on the same entity (static/kinematic use only).
 * Convex, Concave and Mesh build on-demand outlines from their cooked collision
 * geometry: selection-only in Edit, or for every collider when enabled in Play.
 */
export class ColliderComponent extends Component {
  static type = "collider";
  static label = "Collider";
  static tags = ["physics", "play-mode", "3d"];
  static defaults = {
    shape: "box",
    size: [1, 1, 1],
    radius: 0.5,
    height: 1,
    offset: [0, 0, 0],
    rotation: [0, 0, 0],
    autoFit: true,
    autoCenter: true,
    // True only for the visible default inserted by PhysicsSystem.
    autoGenerated: false,
    // Becomes true after the user edits a generated default. Provenance stays
    // intact so collision still collects only geometry owned by this entity.
    autoCustomized: false,
    friction: 0.5,
    restitution: 0,
    isSensor: false,
    // Which collision layer this collider is on. The project's layer matrix
    // (Project Settings → Physics) decides which layers actually interact —
    // that is how a projectile stops hitting the player who fired it.
    layer: "Default",
  };
  static schema = [
    { key: "shape", label: "Shape", type: "select", options: ["box", "sphere", "capsule", "convex", "concave", "mesh", "heightfield"] },
    { key: "layer", label: "Layer", type: "select", options: physicsLayerNames },
    { key: "autoFit", label: "Fit to Mesh", type: "boolean", showIf: (p) => p.shape === "box" || p.shape === "sphere" || p.shape === "capsule" },
    { key: "size", label: "Size", type: "vec3", showIf: (p) => p.shape === "box" && !p.autoFit },
    { key: "radius", label: "Radius", type: "number", min: 0.01, step: 0.05, showIf: (p) => (p.shape === "sphere" || p.shape === "capsule") && !p.autoFit },
    { key: "height", label: "Height", type: "number", min: 0.01, step: 0.05, showIf: (p) => p.shape === "capsule" && !p.autoFit },
    { key: "offset", label: "Offset", type: "vec3" },
    { key: "rotation", label: "Rotation", type: "vec3" },
    { key: "autoCenter", label: "Auto Center", type: "boolean", showIf: (p) => p.shape === "box" || p.shape === "sphere" || p.shape === "capsule" },
    { key: "friction", label: "Friction", type: "number", min: 0, max: 2, step: 0.05 },
    { key: "restitution", label: "Bounciness", type: "number", min: 0, max: 1, step: 0.05 },
    { key: "isSensor", label: "Is Trigger", type: "boolean" },
  ];

  onAttach() {
    this._outlineRequested ??= false;
    this._debugGizmoRequested ??= true;
    this.collider = null; // assigned by PhysicsSystem while playing
    this.colliders = [];
    // See RigidbodyComponent.onAttach: entities arrive after the world is
    // built, and nothing else tells the world they did.
    this.entity.engine?.physics?.markDirty(this.entity, { subtree: false });
    this.#buildGizmo();
    // Heightfield gizmo mirrors the sibling terrain's surface — rebuild it
    // whenever that terrain's heights (or size/resolution) change so the
    // collision preview keeps matching what the user just sculpted.
    if (this.props.shape === "heightfield") {
      this._terrainUnsub = this.entity.engine?.on?.("component-changed", (info) => {
        if (info?.entityId === this.entity.id && info?.componentType === "terrain") this.#rebuildGizmo();
      });
    }
    this._geometryUnsub = this.entity.engine?.on?.("component-changed", (info) => {
      const fittedPrimitive = (this.props.autoCenter || this.props.autoFit)
        && ["box", "sphere", "capsule"].includes(this.props.shape);
      if (fittedPrimitive && info?.entityId === this.entity.id && info?.componentType === "mesh") this.#rebuildGizmo();
    });
    this._modelUnsub = this.entity.engine?.on?.("model-loaded", (entity) => {
      const fittedPrimitive = (this.props.autoCenter || this.props.autoFit)
        && ["box", "sphere", "capsule"].includes(this.props.shape);
      if (fittedPrimitive && entity === this.entity) this.#rebuildGizmo();
    });
    this._cookUnsub = this.entity.engine?.on?.("physics-collider-cooked", (entity) => {
      if (entity !== this.entity || !this._outlineRequested
        || !["convex", "concave", "mesh"].includes(this.props.shape)) return;
      this.#disposeOutline();
      this.#buildOutline();
    });
  }

  onDetach() {
    const physics = this.entity.engine?.physics;
    // Before clearing the handle — that is what the world removes it by.
    physics?.removeEntity(this.entity, { subtree: false });
    physics?.markDirty(this.entity, { subtree: false });
    this.collider = null;
    this.colliders = [];
    this._terrainUnsub?.();
    this._terrainUnsub = null;
    this._geometryUnsub?.();
    this._geometryUnsub = null;
    this._modelUnsub?.();
    this._modelUnsub = null;
    this._cookUnsub?.();
    this._cookUnsub = null;
    this.#disposeGizmo();
    this.#disposeOutline();
  }

  onDisable() {
    if (this.gizmo) this.gizmo.visible = false;
    if (this.outline) this.outline.visible = false;
    const physics = this.entity.engine?.physics;
    physics?.removeEntity(this.entity, { subtree: false });
    physics?.markDirty(this.entity, { subtree: false });
    physics?.invalidateAutoCollider(this.entity);
  }

  onEnable() {
    if (this.gizmo) this.gizmo.visible = this._debugGizmoRequested;
    if (this._outlineRequested) {
      if (this.outline) this.outline.visible = true;
      else this.#buildOutline();
    }
    const physics = this.entity.engine?.physics;
    physics?.invalidateAutoCollider(this.entity);
    physics?.markDirty(this.entity, { subtree: false });
  }

  /**
   * Switching a generated default ON is authoring it (2026-09-02: defaults
   * attach disabled). The automatic pass reaps UNTOUCHED defaults — when a
   * model reloads, or a skin is detected — and would otherwise re-attach the
   * user's enabled collider as a disabled one.
   */
  setEnabled(value) {
    const changed = super.setEnabled(value);
    if (changed && value !== false && this.props.autoGenerated) this.props.autoCustomized = true;
    return changed;
  }

  onPropChanged(key) {
    if (key !== "autoGenerated" && key !== "autoCustomized") this.props.autoCustomized = true;
    super.onPropChanged(key, this.props[key]);
    if (this._outlineRequested) {
      this.#disposeOutline();
      this.#buildOutline();
    }
  }

  #rebuildGizmo() {
    this.#disposeGizmo();
    this.#buildGizmo();
  }

  #buildGizmo() {
    const { shape, size, radius, height, offset, rotation, autoCenter, autoFit } = this.props;
    const bounds = (autoCenter || autoFit) && (shape === "box" || shape === "sphere" || shape === "capsule")
      ? collisionGeometryBounds(this.entity.object3D)
      : null;
    const fitSize = autoFit && bounds ? bounds.getSize(new THREE.Vector3()) : null;
    let geometry = null;
    if (shape === "box") {
      const boxSize = fitSize
        ? [Math.max(fitSize.x, 0.001), Math.max(fitSize.y, 0.001), Math.max(fitSize.z, 0.001)]
        : size;
      geometry = new THREE.EdgesGeometry(new THREE.BoxGeometry(boxSize[0], boxSize[1], boxSize[2]));
    } else if (shape === "sphere") {
      const fittedRadius = fitSize ? fitSize.length() / 2 : radius;
      geometry = new THREE.WireframeGeometry(new THREE.SphereGeometry(fittedRadius, 12, 8));
    } else if (shape === "capsule") {
      const fittedRadius = fitSize ? Math.max(fitSize.x, fitSize.z) / 2 : radius;
      const fittedHeight = fitSize ? Math.max(fitSize.y - fittedRadius * 2, 0.01) : height;
      geometry = new THREE.WireframeGeometry(new THREE.CapsuleGeometry(fittedRadius, fittedHeight, 4, 8));
    } else if (shape === "heightfield") {
      geometry = buildHeightfieldWireframe(this.entity);
    }
    if (!geometry) return; // geometry-derived shape: the viewport requests its cooked outline on demand

    this.gizmo = new THREE.LineSegments(
      geometry,
      new THREE.LineBasicMaterial({ color: GIZMO_COLOR, transparent: true, opacity: 0.7, depthWrite: false }),
    );
    this.gizmo.position.fromArray(offset);
    if (autoCenter && (shape === "box" || shape === "sphere" || shape === "capsule")) {
      const center = bounds?.getCenter(new THREE.Vector3());
      if (center) this.gizmo.position.add(center);
    }
    this.gizmo.rotation.set(
      (rotation?.[0] ?? 0) * DEG2RAD,
      (rotation?.[1] ?? 0) * DEG2RAD,
      (rotation?.[2] ?? 0) * DEG2RAD,
    );
    // Defer to scene depth so the wireframe hides behind walls instead of
    // painting over them; the previous `depthTest: false` made colliders
    // look like they sit in front of every solid object in the scene.
    this.gizmo.renderOrder = 1;
    this.gizmo.visible = this.enabled && this._debugGizmoRequested;
    this.gizmo.layers.set(PHYSICS_DEBUG_LAYER);
    this.gizmo.userData.engineOwned = true;
    this.gizmo.userData.editorOnly = true;
    this.gizmo.raycast = () => {}; // never intercept viewport picking
    this.entity.object3D.add(this.gizmo);
  }

  #disposeGizmo() {
    if (!this.gizmo) return;
    this.entity.object3D.remove(this.gizmo);
    this.gizmo.geometry.dispose();
    this.gizmo.material.dispose();
    this.gizmo = null;
  }

  // ---- on-demand outline (convex / reduced concave / exact mesh) ----

  /**
   * Geometry-derived colliders build no permanent wireframe of their own.
   * This traces one on demand: Edit requests only the selected collider, while
   * Play requests every collider when its Colliders layer is enabled.
   *
   * The outline comes from the cooked data actually fed to Rapier, so Convex
   * shows its hulls, Concave its reduced surface, and Mesh every source triangle.
   */
  setOutlineVisible(visible) {
    this._outlineRequested = !!visible;
    if (!visible) return this.#disposeOutline();
    if (!this.enabled) return;
    // Primitive shapes already draw a real gizmo; a second outline on top of
    // one would only z-fight with it.
    if (this.outline || this.gizmo) return;
    this.#buildOutline();
  }

  #buildOutline() {
    if (!this.enabled) return;
    const root = this.entity.object3D;
    const cooked = this.entity.engine?.physics?.getCookedColliderGeometry?.(this.entity);
    if (this.props.shape === "convex") {
      const hulls = cooked?.convexParts?.length
        ? cooked.convexParts
        : cooked?.convex ? [cooked.convex] : [];
      if (!hulls.length) {
        this.entity.engine?.physics?.prewarmAutoColliders?.(this.entity);
        return;
      }
      const positions = [];
      for (const hull of hulls) {
        const surface = new THREE.BufferGeometry();
        surface.setAttribute("position", new THREE.BufferAttribute(hull.vertices, 3));
        surface.setIndex(new THREE.BufferAttribute(hull.indices, 1));
        const edges = new THREE.EdgesGeometry(surface);
        const edgePositions = edges.attributes.position.array;
        for (let i = 0; i < edgePositions.length; i++) positions.push(edgePositions[i]);
        edges.dispose();
        surface.dispose();
      }
      const geometry = new THREE.BufferGeometry().setAttribute(
        "position",
        new THREE.Float32BufferAttribute(positions, 3),
      );
      this.outline = new THREE.LineSegments(
        geometry,
        new THREE.LineBasicMaterial({ color: GIZMO_COLOR, transparent: true, opacity: 0.7, depthWrite: false }),
      );
      this.#placeOutline(root);
      return;
    }
    const surface = this.props.shape === "concave" ? cooked?.concave : cooked;
    if (["concave", "mesh"].includes(this.props.shape)) {
      if (!surface) {
        this.entity.engine?.physics?.prewarmAutoColliders?.(this.entity);
        return;
      }
      const geometry = new THREE.BufferGeometry();
      geometry.setAttribute("position", new THREE.BufferAttribute(surface.vertices, 3));
      geometry.setIndex(new THREE.BufferAttribute(surface.indices, 1));
      const edges = new THREE.EdgesGeometry(geometry);
      geometry.dispose();
      this.outline = new THREE.LineSegments(
        edges,
        new THREE.LineBasicMaterial({ color: GIZMO_COLOR, transparent: true, opacity: 0.7, depthWrite: false }),
      );
      this.#placeOutline(root);
      return;
    }
    root.updateWorldMatrix(true, false);
    // Into the entity's LOCAL frame: the outline is parented to object3D, so
    // the entity's own scale is applied at render. Baking it in here — the way
    // collision collection must, because Rapier shapes cannot scale — would square it.
    const invRoot = new THREE.Matrix4().copy(root.matrixWorld).invert();
    const local = new THREE.Matrix4();
    const v = new THREE.Vector3();
    const positions = [];

    root.traverse((child) => {
      if (!child.isMesh || !child.geometry?.attributes?.position) return;
      if (child.layers.mask === 1 << EDITOR_LAYER) return; // editor-only helper
      child.updateWorldMatrix(true, false);
      local.copy(invRoot).multiply(child.matrixWorld);
      const edges = new THREE.EdgesGeometry(child.geometry);
      const pos = edges.attributes.position;
      for (let i = 0; i < pos.count; i++) {
        v.fromBufferAttribute(pos, i).applyMatrix4(local);
        positions.push(v.x, v.y, v.z);
      }
      edges.dispose();
    });
    if (!positions.length) return;

    this.outline = new THREE.LineSegments(
      new THREE.BufferGeometry().setAttribute("position", new THREE.Float32BufferAttribute(positions, 3)),
      new THREE.LineBasicMaterial({ color: GIZMO_COLOR, transparent: true, opacity: 0.7, depthWrite: false }),
    );
    this.#placeOutline(root);
  }

  /** Applies the editor viewport's visual-only Colliders layer state. */
  setDebugVisible(gizmoVisible, outlineVisible = gizmoVisible) {
    this._debugGizmoRequested = !!gizmoVisible;
    if (this.gizmo) this.gizmo.visible = this.enabled && this._debugGizmoRequested;
    // Preserve the layer request while disabled. onEnable builds/restores the
    // outline so a component eye-toggle cannot desynchronise the Layers menu.
    this.setOutlineVisible(!!outlineVisible);
  }

  #placeOutline(root) {
    // Geometry-derived shapes keep their authored vertex offsets, then apply
    // this optional collider-local pose on top.
    this.outline.position.fromArray(this.props.offset ?? [0, 0, 0]);
    this.outline.rotation.set(
      (this.props.rotation?.[0] ?? 0) * DEG2RAD,
      (this.props.rotation?.[1] ?? 0) * DEG2RAD,
      (this.props.rotation?.[2] ?? 0) * DEG2RAD,
    );
    this.outline.renderOrder = 1;
    this.outline.visible = this.enabled;
    this.outline.layers.set(PHYSICS_DEBUG_LAYER);
    this.outline.userData.engineOwned = true;
    this.outline.userData.editorOnly = true;
    this.outline.raycast = () => {}; // never intercept viewport picking
    root.add(this.outline);
  }

  #disposeOutline() {
    if (!this.outline) return;
    this.entity.object3D.remove(this.outline);
    this.outline.geometry.dispose();
    this.outline.material.dispose();
    this.outline = null;
  }
}

/**
 * Wireframe that traces the sibling Terrain's collision surface, for the
 * `heightfield` collider shape. Sampled on a coarse grid (the full heightmap
 * would be far too dense as line segments) at the terrain's live heights, and
 * lifted a hair above the surface to avoid z-fighting. Returns null if the
 * entity has no Terrain component yet (e.g. the collider was added first).
 */
function buildHeightfieldWireframe(entity) {
  const terrain = entity?.getComponent?.("terrain");
  if (!terrain?.heightsArray || typeof terrain.heightAtLocal !== "function") return null;
  const size = terrain.props?.size ?? 50;
  const segments = Math.min(32, Math.max(2, terrain.resolution ?? 32));
  const plane = new THREE.PlaneGeometry(size, size, segments, segments);
  plane.rotateX(-Math.PI / 2);
  const pos = plane.getAttribute("position");
  for (let i = 0; i < pos.count; i++) {
    pos.setY(i, terrain.heightAtLocal(pos.getX(i), pos.getZ(i)) + 0.02);
  }
  pos.needsUpdate = true;
  const wire = new THREE.WireframeGeometry(plane);
  plane.dispose();
  return wire;
}
